name: sc2ts-slim
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - slim>=5
  - snakemake-minimal
  - click
  - numpy
  - pandas
  - pytest
  - pip
  - pip:
      - pyslim
      - tscompare
      # 1.1 adds custom reference genomes (reference_fasta).
      - sc2ts[inference]>=1.1
