#!/usr/bin/env python3
r"""
Generate the LaTeX source for the Pango X copying patterns figure
(Figure~\ref{fig:pango_x_copying_patterns} in main.tex).

Event names and types are read from data/pango_x_event_details.csv, and the
copying pattern images are those written to figures/static by
src/save_copying_patterns.py. The figure is a tabularray ``longtabs`` table,
which breaks over pages, written to figure.tex and pulled into main.tex with

    \input{copying_patterns/figure.tex}

Run it from anywhere; paths are resolved relative to this file:

    python3 copying_patterns/make_figure.py

Only the standard library is used, so it runs under any python3 without the
project environment. Rows are in the order of the CSV (recombination node ID)
within each event type.
"""

import argparse
import csv
import pathlib

HERE = pathlib.Path(__file__).parent
REPO = HERE.parent.parent
DETAILS_CSV = REPO / "data" / "pango_x_event_details.csv"
STATIC_DIR = REPO / "figures" / "static"

# src/save_copying_patterns.py does not draw events with more parents than this
MAX_PARENTS = 4
IMAGE_HEIGHT = "1.5em"
LATEX_SPECIALS = set("#$%&_^~\\{}")

SECTION_TITLES = {
    1: "Type I events: Recombination coinciding with Pango origin node",
    2: "Type II events: Recombination closely associated with Pango lineage(s)",
}


def read_events():
    with open(DETAILS_CSV, newline="") as f:
        return list(csv.DictReader(f))


def check_safe(name):
    bad = sorted(LATEX_SPECIALS & set(name))
    if bad:
        raise ValueError(
            f"name={name!r} contains LaTeX special character(s) "
            f"{''.join(bad)!r} that make_figure.py does not escape"
        )
    return name


def image_name(name):
    # Same mapping as save_copying_pattern_image in src/save_copying_patterns.py
    return name.replace("/", "+") + ".png"


def make_caption(num_shown, omitted):
    caption = (
        f"Copying patterns for the {num_shown} recombination events associated "
        r"with Pango X lineages listed in Table~\ref{tab:pango_x_lineages}, "
        "ordered by label within each event type. "
        "The ID of the recombination node is shown to the right of each "
        "copying pattern."
    )
    if omitted:
        names = ", ".join(
            f"{row['name']} ({row['num_parents']} parents)" for row in omitted
        )
        caption += (
            f" Events with more than {MAX_PARENTS} parents are not shown: "
            f"{names}."
        )
    caption += " See also Document S2 for exact positions and nucleotide bases."
    return caption


def make_figure():
    events = read_events()
    omitted = [row for row in events if int(row["num_parents"]) > MAX_PARENTS]
    shown = [row for row in events if int(row["num_parents"]) <= MAX_PARENTS]
    missing = [
        image_name(row["name"])
        for row in shown
        if not (STATIC_DIR / image_name(row["name"])).exists()
    ]
    if missing:
        raise FileNotFoundError(
            f"copying pattern image(s) missing from {STATIC_DIR}: "
            f"{', '.join(missing)}; rerun src/save_copying_patterns.py"
        )
    types = sorted({int(row["type"]) for row in events})
    unknown = set(types) - set(SECTION_TITLES)
    if unknown:
        raise ValueError(f"unexpected event type(s) {sorted(unknown)}")

    lines = [
        "% Generated by make_figure.py -- do not edit.",
        "% Regenerate with: python3 copying_patterns/make_figure.py",
        "%",
        "% tabularray numbers a long table with the table counter, so within",
        "% this group the table counter and names are aliased to the figure",
        "% ones. The \\refstepcounter is global and so advances the figure",
        "% counter, and the real table counter is back in place after the group.",
        r"\begingroup",
        r"\makeatletter\let\c@table\c@figure\makeatother",
        r"\let\thetable\thefigure",
        r"\let\tablename\figurename",
        r"\begin{longtabs}[",
        r"    theme   = sc2ts,",
        r"    label   = {fig:pango_x_copying_patterns},",
        r"    entry   = none,",
        f"    caption = {{{make_caption(len(shown), omitted)}}},",
        r"  ]{",
        r"    colspec = {Q[c,m]Q[l,m]},",
        r"    rowsep  = 3pt,",
        r"  }",
    ]
    for event_type in types:
        rows = [row for row in shown if int(row["type"]) == event_type]
        rows.sort(key=lambda row: row["name"])
        rule = r"\toprule" if event_type == types[0] else r"\midrule"
        lines.append(
            rf"{rule} \SetCell[c=2]{{l}} \textbf{{{SECTION_TITLES[event_type]}}} \\"
        )
        for i, row in enumerate(rows):
            # Keep the banner with at least its first row
            prefix = r"\nopagebreak " if i == 0 else ""
            lines.append(
                f"{prefix}{check_safe(row['name'])} & "
                rf"\includegraphics[height={IMAGE_HEIGHT}]"
                f"{{static/{image_name(row['name'])}}} \\\\"
            )
    lines.append(r"\bottomrule")
    lines.append(r"\end{longtabs}")
    lines.append(r"\endgroup")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=pathlib.Path,
        default=HERE / "figure.tex",
        help="where to write the generated LaTeX (default: %(default)s)",
    )
    args = parser.parse_args()
    args.output.write_text(make_figure())
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
