

rule download_json:
    output:
        "tree.all_viridian.202409.jsonl.gz"
    shell:
        """
        wget --quiet --content-disposition \
            https://figshare.com/ndownloader/files/49691040 \
            -O {output}
        """

rule download_pb:
    output:
        "tree.all_viridian.202409.pb.gz"
    shell:
        """
        wget --quiet --content-disposition \
            https://figshare.com/ndownloader/files/49691037 \
            -O {output}
        """


rule decompress_tree:
    input:
        "tree.all_viridian.202409.jsonl.gz"
    output:
        "tree.all_viridian.202409.jsonl"
    shell:
        "gunzip -k {input}"


rule convert_topology:
    input:
        "tree.all_viridian.202409.jsonl.gz"
    output:
        "viridian.topology.trees"
    shell:
        "python ../src/mat2tsk.py convert-topology {input} {output}"

