#!/usr/bin/env python3
r"""
Generate the LaTeX source for the table of Pango X lineages absent from the
ARG in main.tex (Table~\ref{tab:extra_hmm_results}).

The CSV file in this directory is the interface to the analysis: it is
written by notebooks/analysis_matches_pango_x.ipynb. This script turns it into
table.tex, which main.tex pulls in with \input.

Run it from anywhere; paths are resolved relative to this file:

    python3 absent_pango_x_table/make_table.py

Only the standard library is used, and row order is taken from the CSV file,
following ripples_tables/make_tables.py.
"""

import csv
import pathlib

HERE = pathlib.Path(__file__).parent
LATEX_SPECIALS = set("#$%&_^~\\{}")
HEADER = [
    "% Generated by make_table.py -- do not edit.",
    "% Regenerate with: python3 absent_pango_x_table/make_table.py",
]

CAPTION = r"""
Sc2ts HMM results for Pango X lineages absent from the ARG.
Lineages are grouped with their sublineages using the updated (v1.29) Pango
assignments in the Viridian metadata, and are included if no sample in the ARG
is assigned to the lineage or any of its sublineages.
For each lineage we show the number of samples in the dataset within the
inference date range; the number of these that passed sample quality control
and were matched by the HMM during primary inference; the number of
breakpoints and the HMM cost of these matches; and the most common combination
of parent lineages in the matches (with the number of samples, if not all).
Ranges are shown where samples differ.
All matched samples had HMM costs above the threshold of 7 required for
inclusion in the ARG.
"""


def check_safe(value):
    """
    Pass a CSV value through, raising if it contains LaTeX special characters.
    """
    bad = sorted(LATEX_SPECIALS & set(value))
    if bad:
        raise ValueError(f"{value!r} contains LaTeX special character(s) {bad}")
    return value


def make_row(cells):
    return " & ".join(str(c) for c in cells) + r" \\"


def table():
    with open(HERE / "absent_pango_x.csv", newline="") as f:
        rows = list(csv.DictReader(f))
    lines = HEADER + [
        r"\begin{table}",
        r"\caption{",
        " ".join(CAPTION.split()),
        r"}",
        r"\label{tab:extra_hmm_results}",
        r"\centering",
        r"\footnotesize",
        r"\begin{tabular}{lrrccl}",
        r"\toprule",
        make_row(["Pango", "Samples", "Matched", "Breakpoints", "HMM cost", "Parents"]),
        r"\midrule",
    ]
    for row in rows:
        lines.append(
            make_row(
                [
                    check_safe(row["pango"]),
                    int(row["samples"]),
                    int(row["matched"]),
                    check_safe(row["breakpoints"]),
                    check_safe(row["hmm_cost"]),
                    check_safe(row["parents"]),
                ]
            )
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def main():
    path = HERE / "table.tex"
    path.write_text(table())
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
