#!/usr/bin/env python3
r"""
Generate the LaTeX source for the two UShER+RIPPLES tables in main.tex
(Table~\ref{tab:ripples_x_lineages} and
Table~\ref{tab:ripples_sc2ts_event_descendants}).

The CSV files in this directory are the interface to the analysis: they are
written by notebooks/analysis_ripples.ipynb. This script turns them into
x_lineages.tex and event_descendants.tex, which main.tex pulls in with \input.

Run it from anywhere; paths are resolved relative to this file:

    python3 ripples_tables/make_tables.py

Only the standard library is used, and row order is taken from the CSV files,
following pango_x_table/make_table.py.
"""

import ast
import csv
import pathlib

HERE = pathlib.Path(__file__).parent
LATEX_SPECIALS = set("#$%&_^~\\{}")
HEADER = [
    "% Generated by make_tables.py -- do not edit.",
    "% Regenerate with: python3 ripples_tables/make_tables.py",
]

X_LINEAGES_CAPTION = r"""
RIPPLES events associated with Pango X lineages.
Each row is a recombination event identified by RIPPLES (at $p=3$) in which
Pango X lineages appear, along with the corresponding sc2ts event and its type
from Table~\ref{tab:pango_x_lineages}, where applicable.
Events also present at $p=4$ are indicated.
Clades are matched by finding the most recent common ancestor of the samples
associated with each UShER+RIPPLES event in the sc2ts ARG.
The clade difference is the number of additional samples descending from this
node, and the path length is the number of edges between it and its closest
recombinant ancestor.
The descendants column shows the number of samples in the UShER clade by
Pango lineage, with sublineages of X lineages counted under the X lineage.
"""

X_LINEAGES_GROUPS = {
    "equivalent": "Equivalent sc2ts and RIPPLES recombination events",
    "descendant": "RIPPLES recombination event descends from sc2ts recombination event",
    "non_recombinant": "RIPPLES recombination event equivalent to sc2ts non-recombinant node",
    "not_comparable": "RIPPLES recombination event not comparable to sc2ts",
}

EVENT_DESCENDANTS_CAPTION = r"""
Distribution of numbers of descendants for UShER+RIPPLES events and sc2ts.
The first column shows the number of descendants (binned for larger values)
and the others show the corresponding number of events.
"""


def read_csv(name):
    with open(HERE / name, newline="") as f:
        return list(csv.DictReader(f))


def check_safe(value):
    """
    Pass a CSV value through, raising if it contains LaTeX special characters.
    """
    bad = sorted(LATEX_SPECIALS & set(value))
    if bad:
        raise ValueError(f"{value!r} contains LaTeX special character(s) {bad}")
    return value


def fmt_descendants(value):
    """
    Render the repr of a {pango: count} dict as, e.g., XC:5, B.1.617.2:1.
    """
    counts = ast.literal_eval(value)
    return ", ".join(f"{check_safe(k)}:{v}" for k, v in counts.items())


def make_row(cells):
    return " & ".join(str(c) for c in cells) + r" \\"


def x_lineages_table():
    caption = " ".join(X_LINEAGES_CAPTION.split())
    num_cols = 7
    lines = HEADER + [
        r"\begingroup\scriptsize",
        r"\begin{longtabs}[",
        r"    theme   = sc2ts,",
        r"    label   = {tab:ripples_x_lineages},",
        r"    entry   = {RIPPLES events associated with Pango X lineages},",
        rf"    caption = {{{caption}}},",
        r"  ]{",
        r"    colspec = {llcrrrX[l]},",
        r"    width   = \linewidth,",
        r"    colsep  = 4pt,",
        r"    rowhead = 1,",
        r"  }",
        r"\toprule",
        make_row(
            [
                "sc2ts event",
                "type",
                "in $p=4$",
                "UShER desc",
                "path len",
                "clade diff",
                "descendants",
            ]
        ),
    ]
    group = None
    for row in read_csv("x_lineages.csv"):
        if row["group"] != group:
            group = row["group"]
            title = X_LINEAGES_GROUPS[group]
            lines.append(rf"\midrule \SetCell[c={num_cols}]{{l}} \textbf{{{title}}} \\")
        lines.append(
            make_row(
                [
                    check_safe(row["sc2ts_event"]),
                    check_safe(row["sc2ts_type"]),
                    r"$\checkmark$" if row["in_p4"] == "True" else "",
                    int(row["usher_num_descendants"]),
                    row["path_len"],
                    int(row["clade_diff"]),
                    fmt_descendants(row["descendants"]),
                ]
            )
        )
    lines += [r"\bottomrule", r"\end{longtabs}", r"\endgroup"]
    return "\n".join(lines) + "\n"


def event_descendants_table():
    rows = read_csv("event_descendants.csv")
    last = rows[-1]["descendants"]
    assert last.endswith("+")
    lines = HEADER + [
        r"\begin{table}",
        r"\caption{",
        EVENT_DESCENDANTS_CAPTION.strip(),
        r"}",
        r"\label{tab:ripples_sc2ts_event_descendants}",
        r"\centering",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Count & RIPPLES $p=3$ & RIPPLES $p=4$ & sc2ts \\",
        r"\midrule",
    ]
    for row in rows:
        label = check_safe(row["descendants"]).replace("-", "--")
        if label.endswith("+"):
            label = rf"$\geq$ {label[:-1]}"
        lines.append(make_row([label, int(row["p3"]), int(row["p4"]), int(row["sc2ts"])]))
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def main():
    for name, table in [
        ("x_lineages.tex", x_lineages_table()),
        ("event_descendants.tex", event_descendants_table()),
    ]:
        path = HERE / name
        path.write_text(table)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
