# Paths (relative to simulations/)
reference_fasta: "../arg_postprocessing/NC_045512v2.fa"


# SANTA-SIM settings
# Number of simulation replicates
num_replicates: 1

# Mutation and recombination rates
mutation_rates:
  - "1E-6"
  - "5E-6"
  - "1E-5"
recombination_rates:
  - "1E-6"
  - "5E-6"
  - "1E-5"

# Sampling scheme
# Assume only 1 epoch and 1 generation = 1 day.
generation_count: 30
at_frequency: # Generations
  - 3
  - 5
  - 7
population_size: 500
sample_size: 10


# Sc2ts settings
# Resources
num_threads: 80
memory_limit: 250

# Inference
k_values:
  - 3
  - 4
  - 5

# Filtering
hmm_cost_threshold: 20
max_missing_sites: 0
deletions_as_missing: "true"

# Retrospective sample grouping
min_group_size: 3
min_root_mutations: 2
max_recurrent_mutations: 2
max_mutations_per_sample: 5
retrospective_window: 30
